version: '3.8'

services:
  my-postgres:
    restart: on-failure
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_DB: springAuth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pleasecomein
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  my-keycloak:
    restart: on-failure
    image: keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_HOSTNAME_STRICT: false
    ports:
      - "8080:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm

volumes:
  postgres-data:
