spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/springAuth
    username: postgres
    password: pleasecomein
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Yahor
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Yahor
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: yahor-api
            client-secret: RTH2SuOaJXK8adVFyVv7v7dyKH9tKajZ
            scope: openid
  web:
    resources:
      add-mappings: true

server:
  port: 8081